### ISSUE TITLE
Full yaml example

### ISSUE THREAD

**Issue by GoSpursGoNL** [tfyoung/esphome-MHIHeatPump#1]
Thanks for your efforts! Would you be able to provide a full yaml example for ESPHome? I'm having trouble understanding what things to add to the snippet that you provided. Thanks in advance!

**Comment by tfyoung** [comment]
I didn't take out much. Here's my full yaml, with ips/secrets removed
```
substitutions:
  name: acloungemhi
  friendly_name: Lounge AC
  device_id: mhiac_lounge

esphome:
  name: acloungemhi
  platform: ESP8266
  board: d1_mini
  includes:
    
external_components:
  - source: github://tfyoung/esphome-MHIHeatPump

time:
  - platform: homeassistant
    id: homeassistant_time

wifi:
  ssid: "wifinetwork"
  password: "wifipassword"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

MHIHeatPump:
  id: ${device_id}

climate:
  - platform: MHIHeatPump
    id: lounge
    name: "${friendly_name}"
    mhi_heatpump_id: ${device_id}

sensor:
  - platform: MHIHeatPump
    mhi_heatpump_id: ${device_id}
    outdoor_temperature:
      name: "Outdoor Temperature"
    current:
      id: current
      name: "Current"
  - platform: template
    name: ${friendly_name} power
    id: "power"
    lambda: return id(current).state * 230;  #I think all units are 230V; real voltage can vary a bit, but has a small impact.
    unit_of_measurement: W
    device_class: energy
  - platform: total_daily_energy
    name: ${friendly_name} daily energy
    power_id: "power"
    unit_of_measurement: Wh
    device_class: energy

web_server:
```

The only sections you should definitely need to add are the `wifi`, `esphome` and `api`.

**Comment by GoSpursGoNL** [comment]
Thanks very much. I noticed the ESPHome release of earlier this month allows for specifying a friendly_name under esphome: , so no need for a substition for that anymore it seems, and you then don't need to prepend it to the various entity names anymore in the yaml.
https://esphome.io/changelog/2023.2.0.html#friendly-name

**Comment by deku-m** [comment]
And the part with total_daily_energy:

```
    power_id: "power"
    filters:
        # Multiplication factor from W to kW is 0.001
        - multiply: 0.001
        - throttle: 300s
    unit_of_measurement: kWh
    device_class: energy
```
Convert to kWh? As the energy dashboard of Home Assistant is using kWh.
